// Shared numerology data used by all tool pages

export const LIFE_PATH_DETAILS = {
  1: { title: 'The Pioneer & Leader', planet: 'Sun', element: 'Fire', traits: 'Independent, ambitious, creative, self-reliant, innovative', desc: 'Life Path 1 represents the path of leadership and individuality. You are a natural-born pioneer, driven by an intense desire to create, lead, and chart your own path. You thrive on independence and possess the courage to stand alone in your convictions. Your primary challenge is managing your ego, impatience, and avoiding arrogance.', blog: '/blog/life-path-number-1-complete-personality-and-destiny-guide' },
  2: { title: 'The Peacemaker & Diplomat', planet: 'Moon', element: 'Water', traits: 'Sensitive, cooperative, intuitive, empathetic, tactful', desc: 'Life Path 2 represents the path of harmony, cooperation, and partnership. You are highly sensitive, intuitive, and work best in collaboration. You possess a unique ability to see multiple perspectives and resolve conflicts peacefully. Your primary challenge is overcoming self-doubt, over-sensitivity, and learning to assert your own needs.', blog: '/blog/life-path-number-2-complete-personality-and-destiny-guide' },
  3: { title: 'The Creative Communicator', planet: 'Jupiter', element: 'Air', traits: 'Expressive, artistic, optimistic, social, charismatic', desc: 'Life Path 3 represents the path of self-expression, creativity, and joy. You are naturally expressive, artistic, and have a gift for communication, whether through writing, speaking, art, or performing. You bring optimism and lightness to those around you. Your primary challenge is scattered focus, superficiality, and managing emotional highs and lows.', blog: '/blog/life-path-number-3-complete-personality-and-destiny-guide' },
  4: { title: 'The Builder & Organizer', planet: 'Rahu / Uranus', element: 'Earth', traits: 'Practical, disciplined, systematic, loyal, hardworking', desc: 'Life Path 4 represents the path of stability, hard work, and process. You are the builder of society, offering solid organization, dependability, and system. You value security, honesty, and structure, and are highly committed to your family and work. Your primary challenge is avoiding rigidity, stubbornness, and a tendency to get bogged down in details.', blog: '/blog/life-path-number-4-complete-personality-and-destiny-guide' },
  5: { title: 'The Free Spirit & Explorer', planet: 'Mercury', element: 'Air', traits: 'Adaptable, adventurous, dynamic, progressive, freedom-loving', desc: 'Life Path 5 represents the path of change, adventure, and freedom. You are a versatile explorer who thrives on variety, travel, and sensory experience. You are highly adaptable and progressive, resisting confinement or routine. Your primary challenge is restlessness, lack of direction, impulsiveness, and avoiding escapism.', blog: '/blog/life-path-number-5-complete-personality-and-destiny-guide' },
  6: { title: 'The Nurturer & Provider', planet: 'Venus', element: 'Earth / Water', traits: 'Responsible, compassionate, artistic, family-oriented, helpful', desc: "Life Path 6 represents the path of responsibility, service, and nurturing. You are naturally protective, loving, and focused on creating harmony at home and in your community. You possess a strong aesthetic sense and a desire to heal or teach. Your primary challenge is interfering in others' lives, perfectionism, and taking on too much responsibility.", blog: '/blog/life-path-number-6-complete-personality-and-destiny-guide' },
  7: { title: 'The Seeker & Analyst', planet: 'Ketu / Neptune', element: 'Water / Air', traits: 'Analytical, spiritual, introspective, wise, independent', desc: 'Life Path 7 represents the path of truth, analysis, and spiritual exploration. You are a deep thinker, researcher, and seeker of hidden wisdom. You prefer solitude, nature, and quiet environments to process your thoughts and connect with your intuition. Your primary challenge is emotional distance, skepticism, over-thinking, and difficulty trusting others.', blog: '/blog/life-path-number-7-complete-personality-and-destiny-guide' },
  8: { title: 'The Powerhouse & Achiever', planet: 'Saturn', element: 'Fire / Earth', traits: 'Authoritative, practical, ambitious, resilient, balance-seeking', desc: 'Life Path 8 represents the path of power, material success, and karmic balance. You possess executive ability, business acumen, and a deep resilience to overcome obstacles. You are here to learn the balance between material achievement and spiritual wisdom. Your primary challenge is obsessing over power, status, workaholism, and emotional expression.', blog: '/blog/life-path-number-8-complete-personality-and-destiny-guide' },
  9: { title: 'The Humanitarian & Visionary', planet: 'Mars', element: 'Fire / Water', traits: 'Compassionate, generous, idealistic, universal, dramatic', desc: 'Life Path 9 represents the path of universal love, compassion, and completion. You are a natural humanitarian who feels a deep concern for the world. You are creative, broad-minded, and possess a wisdom that spans multiple dimensions. Your primary challenge is letting go of the past, dealing with emotional disappointments, and avoiding self-sacrifice.', blog: '/blog/life-path-number-9-complete-personality-and-destiny-guide' },
  11: { title: 'The Master Intuitive & Messenger', planet: 'Moon / Neptune', element: 'Water', traits: 'Spiritually aware, inspiring, visionary, sensitive, charismatic', desc: 'Master Number 11 represents the path of spiritual illumination and intuitive messaging. You act as a bridge between the physical and spiritual realms, possessing intense sensitivity and psychic awareness. You are here to inspire others by living your truth. Your primary challenge is managing extreme nervous energy, anxiety, and self-doubt.', blog: '/blog/life-path-master-number-11-complete-guide' },
  22: { title: 'The Master Builder', planet: 'Rahu / Uranus', element: 'Earth', traits: 'Visionary, practical, powerful, systematic, large-scale creator', desc: 'Master Number 22 represents the path of the Master Builder. You have the unique ability to take spiritual visions and manifest them into physical reality on a massive scale. You are practical, highly organized, and capable of leading large projects. Your primary challenge is the immense pressure of your potential, fear of failure, and over-work.', blog: '/blog/life-path-master-number-22-complete-guide' },
  33: { title: 'The Master Teacher', planet: 'Venus / Jupiter', element: 'Water / Fire', traits: 'Compassionate, healing, loving, spiritually protective, nurturing', desc: 'Master Number 33 represents the path of the Master Teacher and Healer. You possess the highest level of compassionate responsibility, dedicated to the spiritual upliftment of humanity. You lead through unconditional love, creative expression, and service. Your primary challenge is taking on the emotional burdens of the entire world and self-neglect.', blog: '/blog/life-path-master-number-33-complete-guide' },
};

export const CHALDEAN_MAP = {
  a: 1, i: 1, j: 1, q: 1, y: 1,
  b: 2, k: 2, r: 2,
  c: 3, g: 3, l: 3, s: 3,
  d: 4, m: 4, t: 4,
  e: 5, h: 5, n: 5, x: 5,
  u: 6, v: 6, w: 6,
  o: 7, z: 7,
  f: 8, p: 8,
};

export const PYTHAGOREAN_MAP = {
  a: 1, j: 1, s: 1,
  b: 2, k: 2, t: 2,
  c: 3, l: 3, u: 3,
  d: 4, m: 4, v: 4,
  e: 5, n: 5, w: 5,
  f: 6, o: 6, x: 6,
  g: 7, p: 7, y: 7,
  h: 8, q: 8, z: 8,
  i: 9, r: 9,
};

export const NAME_NUMBER_DETAILS = {
  1: { title: 'Independence & Vitality', planet: 'Sun', desc: 'A Name Number of 1 carries solar energy, projecting leadership, independence, and strong ambition. It is excellent for personal growth, career advancement, and projecting a confident, authoritative public image. It attracts focus and respect.' },
  2: { title: 'Harmony & Cooperation', planet: 'Moon', desc: 'A Name Number of 2 carries lunar energy, projecting diplomacy, sensitivity, and cooperation. It represents partnerships, artistic expression, and supportive environments. In branding, it is ideal for counseling, customer-facing roles, or art.' },
  3: { title: 'Growth & Creative Expression', planet: 'Jupiter', desc: 'A Name Number of 3 carries Jovial energy, representing expansion, creativity, joy, and active communication. It is highly fortunate, attracting popularity, abundance, and friendly connections. Great for media, writers, and public speakers.' },
  4: { title: 'Structure & Discipline', planet: 'Rahu / Uranus', desc: 'A Name Number of 4 represents Rahu energy, projecting practical discipline, routine, systematic work, and unconventional breakthroughs. It requires hard work and can bring sudden changes. It represents strong organization and building foundations.' },
  5: { title: 'Versatility & Communication', planet: 'Mercury', desc: 'A Name Number of 5 carries Mercurian energy, projecting fast-paced activity, intelligence, adaptability, and high salesmanship. It is extremely popular in business naming as it attracts movement, communication, and fast growth.' },
  6: { title: 'Luxury, Art & Comfort', planet: 'Venus', desc: 'A Name Number of 6 carries Venusian energy, representing love, beauty, luxury, domestic harmony, and financial flow. It is highly magnetic, projecting warmth and trust. Excellent for names in design, beauty, relationships, and wellness.' },
  7: { title: 'Wisdom & Analytical Depth', planet: 'Ketu / Neptune', desc: 'A Name Number of 7 carries Ketu energy, projecting introspection, analysis, research, and deep spiritual awareness. It is a mystical number that values truth over material gain. Ideal for researchers, academics, philosophers, and spiritual consultants.' },
  8: { title: 'Wealth & Karmic Authority', planet: 'Saturn', desc: 'A Name Number of 8 carries Saturnian energy, representing material power, financial mastery, executive leadership, and deep resilience. It is a heavy, ambitious number that brings rewards after testing. Best suited for finance, law, and large systems.' },
  9: { title: 'Humanitarian Courage', planet: 'Mars', desc: 'A Name Number of 9 carries Martian energy, projecting courage, humanitarian values, universal completion, and dynamic power. It attracts active growth, endings, and completions. Good for non-profits, sports, healing, and coaching.' },
  11: { title: 'Master Spiritual Messenger', planet: 'Moon / Neptune', desc: 'Master Number 11 in a name indicates a high spiritual charge, acting as an inspiring catalyst for others. It carries intense intuition and sensitivity. It projects visionary ideals and charisma, though it requires grounding to manage stress.' },
  22: { title: 'Master Builder & Visionary', planet: 'Rahu / Uranus', desc: 'Master Number 22 in a name projects the energy of large-scale physical creation. It combines the practical dedication of 4 with a visionary master plan. It attracts opportunities to build systems, organizations, or structures that benefit humanity.' },
  33: { title: 'Master Nurturer & Spiritual Guide', planet: 'Venus / Jupiter', desc: 'Master Number 33 in a name carries an extremely high vibration of healing and unconditional service. It projects deep protective care, teaching ability, and spiritual wisdom. It attracts trust and is ideal for major teachers, guides, and humanitarians.' },
};

export const BUSINESS_NUMBER_DETAILS = {
  1: { title: 'Leadership & Pioneering Success', planet: 'Sun', bestFor: 'Startups, tech, consultancy, personal brands', desc: 'Business name number 1 attracts leadership energy, authority, and trailblazing success. Ideal for businesses that want to stand out as industry firsts. Clients see you as a dominant, trustworthy authority.', score: 90 },
  2: { title: 'Partnership & Client Trust', planet: 'Moon', bestFor: 'Counselling, beauty, healthcare, customer service', desc: 'Business name number 2 projects emotional warmth, trust, and sensitivity. Excellent for businesses built on relationships and care. Attracts loyal, repeat customers who feel genuinely supported.', score: 78 },
  3: { title: 'Creativity & Rapid Growth', planet: 'Jupiter', bestFor: 'Marketing, media, design, entertainment, coaching', desc: 'Business name number 3 is one of the most auspicious for commercial ventures. It attracts expansion, joyful clients, and creative opportunities at a fast pace. Excellent for social media and content businesses.', score: 92 },
  4: { title: 'Discipline & Structural Strength', planet: 'Rahu / Uranus', bestFor: 'Engineering, construction, IT, accounting', desc: 'Business name number 4 projects reliability, structure, and disciplined work ethic. The business is seen as dependable. Growth may be slower but extremely stable. Avoid this if rapid growth is the primary goal.', score: 70 },
  5: { title: 'Versatility & Opportunity Magnet', planet: 'Mercury', bestFor: 'Sales, trade, e-commerce, travel, events', desc: 'Business name number 5 is the most versatile commercial number. It attracts diverse clients, fast communication, and multiple revenue streams. Excellent for B2C businesses and anything requiring frequent client interaction.', score: 95 },
  6: { title: 'Luxury, Beauty & Loyalty', planet: 'Venus', bestFor: 'Fashion, hospitality, wellness, real estate, food', desc: 'Business name number 6 attracts luxury clientele, aesthetic appreciation, and strong emotional loyalty. Clients feel comfortable, valued, and at home. Excellent for premium-positioning businesses.', score: 88 },
  7: { title: 'Research & Niche Authority', planet: 'Ketu / Neptune', bestFor: 'Research, spirituality, education, analytics, law', desc: 'Business name number 7 attracts a discerning, intellectual clientele and positions the business as a deep authority in its field. Growth is slower but the brand becomes highly respected and trusted for its expertise.', score: 75 },
  8: { title: 'Financial Authority & Power', planet: 'Saturn', bestFor: 'Finance, banking, real estate, large corporations', desc: 'Business name number 8 is the most financially powerful number. It attracts significant revenue, authority, and large-scale clients. However, it demands disciplined management — misuse of power creates rapid decline.', score: 85 },
  9: { title: 'Humanitarian Impact & Universal Reach', planet: 'Mars', bestFor: 'NGOs, healthcare, coaching, sports, global brands', desc: 'Business name number 9 attracts a broad, universal client base and projects humanitarian values. It is excellent for businesses that want global reach and social impact alongside commercial success.', score: 82 },
};

export const MOBILE_NUMBER_DETAILS = {
  1: { label: 'Sun Vibration', luck: 'Auspicious', desc: 'Brings leadership, authority, independence, and career growth. Excellent for executives, entrepreneurs, and self-employed professionals.' },
  2: { label: 'Moon Vibration', luck: 'Neutral', desc: 'Brings peace, diplomacy, sensitivity, and collaboration. Good for counselors, customer service, and creative partners, but can cause emotional ups and downs.' },
  3: { label: 'Jupiter Vibration', luck: 'Highly Auspicious', desc: 'Attracts wisdom, creative growth, counseling opportunities, and expansion. Excellent for teachers, financial planners, writers, and consultants.' },
  4: { label: 'Rahu Vibration', luck: 'Challenging', desc: 'Brings sudden changes, technical focus, and unconventional ideas. Good for IT, research, and technical consultants, but can cause unexpected expenses or confusion.' },
  5: { label: 'Mercury Vibration', luck: 'Highly Auspicious', desc: 'Brings fast communication, trade, business opportunities, and networking. The most versatile mobile number vibration, highly recommended for business owners and salespeople.' },
  6: { label: 'Venus Vibration', luck: 'Auspicious', desc: 'Attracts luxury, relationship harmony, customer comfort, and beauty. Ideal for artists, designers, luxury retail, and family-focused individuals.' },
  7: { label: 'Ketu Vibration', luck: 'Neutral', desc: 'Promotes analysis, introspection, research, and spiritual growth. Good for researchers and coaches, but can lead to feelings of isolation or lack of communication.' },
  8: { label: 'Saturn Vibration', luck: 'Challenging', desc: "Brings struggle, delays, hard work, and discipline. Saturn's energy tests patience, which can feel heavy for daily communications. Not recommended for commercial sales." },
  9: { label: 'Mars Vibration', luck: 'Auspicious', desc: 'Brings courage, urgency, prompt action, and high energy. Excellent for sports, defense, active coaches, and event planners, but requires checking for anger management.' },
};

// Compatibility matrix: key = `${lp1}-${lp2}` (always lower number first)
export const COMPATIBILITY_DATA = {
  '1-1': { score: 68, label: 'Strong but Clashing', desc: 'Two leaders who both want to be first. Mutual respect exists but power struggles are common. Works when each has their own domain.', strengths: 'Ambition, mutual drive, independence', challenges: 'Ego clashes, competition, stubbornness' },
  '1-2': { score: 88, label: 'Excellent Balance', desc: 'The pioneer and the diplomat make a beautifully balanced pair. LP1 leads, LP2 supports and softens — a classic complementary match.', strengths: 'Balance, mutual support, clear roles', challenges: 'LP2 may feel overshadowed; LP1 needs to listen more' },
  '1-3': { score: 84, label: 'Creative & Inspiring', desc: 'An energetic, creative pairing with strong communication and enthusiasm. Both enjoy self-expression and feed each other\'s passions.', strengths: 'Creativity, inspiration, social energy', challenges: 'Both may lack follow-through; need structured commitments' },
  '1-4': { score: 75, label: 'Stable Ambition', desc: 'LP4\'s discipline grounds LP1\'s pioneering energy. A productive match when both respect their different working styles.', strengths: 'Practicality, ambition, loyalty', challenges: 'LP4 may feel LP1 is reckless; LP1 may feel LP4 is rigid' },
  '1-5': { score: 65, label: 'Exciting but Unstable', desc: 'Both crave freedom and independence, which can make commitment difficult. Exciting chemistry but needs conscious effort to build stability.', strengths: 'Adventure, energy, mutual independence', challenges: 'Lack of grounding, commitment issues, restlessness' },
  '1-6': { score: 82, label: 'Protective Partnership', desc: 'LP6\'s nurturing complements LP1\'s leadership beautifully. LP1 provides direction; LP6 creates the loving home environment.', strengths: 'Family stability, mutual support, warmth', challenges: 'LP6 may become over-protective; LP1 needs more space' },
  '1-7': { score: 74, label: 'Intellectual Respect', desc: 'An unusual but stimulating pairing. LP1 acts; LP7 thinks. Both are independent — this works when each respects the other\'s need for space.', strengths: 'Intellectual depth, mutual independence, growth', challenges: 'Communication gaps; LP7 may seem too withdrawn for LP1' },
  '1-8': { score: 86, label: 'Power Couple', desc: 'A highly driven, successful pairing. Both are ambitious and goal-oriented. Together they can build significant material success.', strengths: 'Success, ambition, financial acuity', challenges: 'Work may dominate; emotional needs can be neglected' },
  '1-9': { score: 80, label: 'Visionary Duo', desc: 'LP1\'s independent leadership combines with LP9\'s universal compassion. A match that can create meaningful impact in the world.', strengths: 'Vision, purpose, generosity', challenges: 'LP9\'s self-sacrifice vs. LP1\'s self-focus; need compromise' },
  '2-2': { score: 72, label: 'Deeply Sensitive', desc: 'A gentle, intuitive pair who deeply understand each other\'s emotional needs. Risk of co-dependency and shared indecision.', strengths: 'Empathy, emotional depth, harmony', challenges: 'Both need a leader; decisions can stall; shared sensitivity' },
  '2-3': { score: 85, label: 'Joyful Harmony', desc: 'LP3\'s creativity and optimism lifts LP2\'s sensitivity into joy. A warm, socially engaged couple with strong communication.', strengths: 'Joy, creativity, warmth, communication', challenges: 'LP3\'s scattered energy may unsettle LP2\'s need for security' },
  '2-4': { score: 80, label: 'Reliable Foundation', desc: 'LP4\'s structure gives LP2 the security they crave. A stable, dependable partnership with clear emotional and practical support.', strengths: 'Security, trust, practical partnership', challenges: 'LP4 may be too emotionally reserved for LP2\'s deep needs' },
  '2-5': { score: 62, label: 'Challenging Differences', desc: 'LP2 craves stability; LP5 needs freedom. These fundamental needs clash unless both are highly conscious and flexible.', strengths: 'Mutual learning, growth through contrast', challenges: 'Commitment vs. freedom; emotional needs vs. independence' },
  '2-6': { score: 94, label: 'Most Compatible', desc: 'The most harmonious combination in numerology. Both are caring, relationship-focused, and devoted to creating a warm, loving home.', strengths: 'Deep love, nurturing, family, loyalty', challenges: 'Both may over-sacrifice; need to maintain individual identities' },
  '2-7': { score: 83, label: 'Spiritual Bond', desc: 'LP7\'s spiritual depth and LP2\'s emotional intuition create a quietly profound connection. They understand each other without words.', strengths: 'Spiritual depth, intuition, quiet understanding', challenges: 'LP7\'s need for solitude may feel like rejection to LP2' },
  '2-8': { score: 78, label: 'Complementary Strengths', desc: 'LP2\'s emotional intelligence balances LP8\'s material focus. Together they build a stable life — LP8 earns, LP2 nurtures.', strengths: 'Stability, practical success, emotional support', challenges: 'LP8\'s work focus may leave LP2 feeling emotionally neglected' },
  '2-9': { score: 84, label: 'Compassionate Pair', desc: 'Both are giving and emotionally oriented. This is a warm, idealistic relationship driven by shared values of service and love.', strengths: 'Compassion, generosity, shared values', challenges: 'Both may neglect practical matters; LP9\'s restlessness unsettles LP2' },
  '3-3': { score: 70, label: 'Creative Chaos', desc: 'Two expressive, social spirits who inspire each other endlessly. However, both lack practicality — the relationship can feel exciting but unfocused.', strengths: 'Creativity, joy, social life, communication', challenges: 'Lack of grounding, financial instability, competition for attention' },
  '3-4': { score: 74, label: 'Balance of Opposites', desc: 'LP4\'s discipline can feel stifling to LP3\'s free spirit, but LP3\'s creativity can inspire LP4. Works with mutual respect.', strengths: 'Balance of creativity and structure', challenges: 'Fundamentally different approaches to life and work' },
  '3-5': { score: 82, label: 'Fun & Adventurous', desc: 'Both love freedom, variety, and self-expression. A vibrant, socially active couple with lots of shared excitement.', strengths: 'Excitement, communication, social energy', challenges: 'Neither provides stability; need to plan finances and future carefully' },
  '3-6': { score: 86, label: 'Warm & Creative', desc: 'LP6\'s nurturing creates the security LP3 needs to flourish creatively. LP3 brings joy into LP6\'s responsible life.', strengths: 'Warmth, creativity, family, mutual appreciation', challenges: 'LP6 may grow weary of LP3\'s lack of commitment to responsibilities' },
  '3-7': { score: 68, label: 'Intellectually Fascinating', desc: 'An unusual pairing — LP3 is social and expressive; LP7 is private and analytical. Fascinating but requires deep understanding.', strengths: 'Intellectual stimulation, growth, unique perspectives', challenges: 'Very different social needs; communication style clash' },
  '3-8': { score: 76, label: 'Ambitious Together', desc: 'LP8\'s ambition and LP3\'s creativity make a commercially successful pair. LP3 brings ideas; LP8 executes with power.', strengths: 'Success, creativity, ambition, social recognition', challenges: 'LP8 may feel LP3 is irresponsible; LP3 may feel LP8 is controlling' },
  '3-9': { score: 90, label: 'Inspirational Match', desc: 'One of the most naturally harmonious pairings. Both are creative, optimistic, and idealistic. They inspire each other constantly.', strengths: 'Inspiration, creativity, compassion, social impact', challenges: 'Both are givers — need to also receive; financial discipline required' },
  '4-4': { score: 72, label: 'Solid but Rigid', desc: 'Extremely stable and loyal, but may lack excitement and spontaneity. A reliable, long-lasting partnership built on shared values.', strengths: 'Stability, loyalty, reliability, trust', challenges: 'Lack of spontaneity; both may be too stubborn to compromise' },
  '4-5': { score: 60, label: 'Challenging Contrast', desc: 'LP4 wants structure and security; LP5 wants freedom and change. This fundamental opposition makes this one of the harder pairings.', strengths: 'Mutual learning, balance of stability and adventure', challenges: 'Deep incompatibility in lifestyle needs; requires great maturity' },
  '4-6': { score: 84, label: 'Stable & Nurturing', desc: 'Both value family, security, and responsibility. A deeply committed partnership with strong foundations and mutual respect.', strengths: 'Family values, stability, loyalty, practicality', challenges: 'Both may be too duty-focused; spontaneity and romance need effort' },
  '4-7': { score: 78, label: 'Thoughtful Pair', desc: 'Two introspective numbers who value truth, quality, and depth. A quiet, intellectually stimulating relationship with deep mutual respect.', strengths: 'Intellectual depth, loyalty, reliability, spiritual growth', challenges: 'Both need emotional expression — may become too practical and detached' },
  '4-8': { score: 87, label: 'Powerfully Productive', desc: 'Both are disciplined, ambitious, and materially focused. A highly effective partnership for building long-term success and financial security.', strengths: 'Material success, discipline, shared ambition, loyalty', challenges: 'Work-life balance; both may neglect emotional and romantic needs' },
  '4-9': { score: 70, label: 'Grounded Vision', desc: 'LP4\'s practical discipline grounds LP9\'s broad idealism. A complementary pair when both respect their different approaches.', strengths: 'Practicality, idealism, loyalty, humanitarian values', challenges: 'LP9\'s restlessness conflicts with LP4\'s need for stability' },
  '5-5': { score: 66, label: 'Exciting & Unpredictable', desc: 'Two freedom-lovers who understand each other perfectly — but may never settle down. This relationship is exciting but needs conscious grounding.', strengths: 'Freedom, excitement, adventure, mutual understanding', challenges: 'No one provides stability; commitment and finances need careful management' },
  '5-6': { score: 72, label: 'Freedom vs. Family', desc: 'LP6 craves stability and family; LP5 needs freedom and change. Can work beautifully when LP6 allows freedom and LP5 commits to home life.', strengths: 'Balance, warmth, excitement', challenges: 'Fundamentally different needs around stability and freedom' },
  '5-7': { score: 70, label: 'Intriguing Opposites', desc: 'LP5\'s outward energy contrasts with LP7\'s inner world. A fascinating pairing when both appreciate their differences.', strengths: 'Intellectual curiosity, growth, unique perspectives', challenges: 'LP5\'s social needs clash with LP7\'s need for solitude' },
  '5-8': { score: 74, label: 'Dynamic & Ambitious', desc: 'Both are driven and energetic in their own ways. LP5 brings versatility and connections; LP8 brings power and strategy.', strengths: 'Energy, ambition, adaptability, success', challenges: 'LP5\'s freedom needs vs. LP8\'s controlling tendencies' },
  '5-9': { score: 82, label: 'Adventurous & Compassionate', desc: 'A lively, freedom-loving pair with shared humanitarian values. Both appreciate the world and want to explore it — together.', strengths: 'Adventure, compassion, freedom, shared values', challenges: 'Neither provides practical stability; need grounded support systems' },
  '6-6': { score: 80, label: 'Devoted & Warm', desc: 'A deeply nurturing pair with shared values of home, family, and service. Can border on co-dependency but is generally a warm, lasting match.', strengths: 'Love, warmth, family devotion, shared values', challenges: 'Over-giving, martyrdom, resistance to change, possessiveness' },
  '6-7': { score: 72, label: 'Warmth & Wisdom', desc: 'LP6\'s warmth creates the safe space LP7 needs to open up. LP7\'s depth adds intellectual richness to LP6\'s nurturing world.', strengths: 'Warmth, depth, loyalty, spiritual growth', challenges: 'LP7\'s need for solitude vs. LP6\'s need for closeness' },
  '6-8': { score: 82, label: 'Provider Pair', desc: 'LP6 creates the home; LP8 creates the wealth. Both are responsible and committed — a highly stable, successful match.', strengths: 'Material success, stability, family, responsibility', challenges: 'LP8\'s work obsession vs. LP6\'s need for quality time together' },
  '6-9': { score: 86, label: 'Loving & Idealistic', desc: 'Both are natural givers with deep compassion and humanitarian values. A beautifully warm relationship guided by love and service.', strengths: 'Love, compassion, shared service, loyalty', challenges: 'Both may neglect self; need to maintain individual boundaries' },
  '7-7': { score: 74, label: 'Deep but Isolated', desc: 'Two seekers who profoundly understand each other\'s need for solitude and truth. Risk of becoming too reclusive together.', strengths: 'Spiritual depth, intellectual connection, mutual understanding', challenges: 'Isolation, emotional distance, difficulty with practicality' },
  '7-8': { score: 76, label: 'Wisdom & Power', desc: 'LP7\'s spiritual depth complements LP8\'s material authority. A quietly powerful pairing when both appreciate their different orientations.', strengths: 'Intelligence, depth, success, mutual respect', challenges: 'LP8\'s materialism vs. LP7\'s spiritual values; communication gaps' },
  '7-9': { score: 80, label: 'Spiritual & Universal', desc: 'Both are introspective and drawn to higher meaning. LP7 seeks inner truth; LP9 seeks universal service. A deeply meaningful pairing.', strengths: 'Spiritual depth, wisdom, compassion, shared ideals', challenges: 'Both may be impractical; financial and material life needs attention' },
  '8-8': { score: 76, label: 'Empire Builders', desc: 'Extremely driven and financially capable. Together they can build significant wealth. Risk of work dominating everything else.', strengths: 'Material success, shared ambition, mutual respect', challenges: 'Power struggles, work obsession, emotional neglect' },
  '8-9': { score: 78, label: 'Power & Purpose', desc: 'LP8\'s material power combines with LP9\'s universal vision. A couple that can create significant worldly impact when aligned.', strengths: 'Success, impact, shared vision, complementary strengths', challenges: 'LP8\'s ego vs. LP9\'s selflessness; different definitions of success' },
  '9-9': { score: 82, label: 'Universal Love', desc: 'Two compassionate, idealistic souls united in service and love. A deeply meaningful relationship guided by shared humanitarian values.', strengths: 'Compassion, creativity, idealism, universal love', challenges: 'Both may give so much to the world they neglect each other' },
};

export const PERSONAL_YEAR_DETAILS = {
  1: { title: 'Year of New Beginnings', theme: 'Start, initiate, plant seeds', desc: 'This is your year to start fresh. Ideal for launching businesses, starting relationships, moving to a new city, or making bold decisions. The universe strongly supports new beginnings this year.', doThis: 'Take initiative, be bold, start projects', avoidThis: 'Waiting, hesitating, clinging to the past', bestMonths: '1, 5, 9' },
  2: { title: 'Year of Partnership', theme: 'Cooperate, be patient, connect', desc: 'A year for relationships, partnerships, and patience. Growth happens through cooperation not force. Focus on building connections, deepening existing relationships, and developing your intuition.', doThis: 'Nurture relationships, listen more, be patient', avoidThis: 'Forcing outcomes, rushing decisions, isolation', bestMonths: '2, 6, 11' },
  3: { title: 'Year of Creative Expression', theme: 'Express, create, socialise', desc: 'Your most expressive and social year. Creative projects flourish, social opportunities expand, and your natural charisma is at its peak. Ideal for writing, speaking, performing, or any form of self-expression.', doThis: 'Create, communicate, socialise, speak your truth', avoidThis: 'Scattered energy, gossip, superficiality', bestMonths: '3, 6, 9' },
  4: { title: 'Year of Building & Structure', theme: 'Organise, work hard, stabilise', desc: 'A year to lay solid foundations. Hard work and discipline are rewarded. Focus on systems, health, finances, and long-term projects. This is a building year — not glamorous, but essential.', doThis: 'Organise, save money, complete unfinished projects', avoidThis: 'Cutting corners, ignoring health, making impulsive changes', bestMonths: '4, 8, 22' },
  5: { title: 'Year of Change & Freedom', theme: 'Adapt, explore, embrace change', desc: 'Expect significant changes this year — often unexpected. Travel, career shifts, relationship transitions, and exciting new opportunities appear. Flexibility is your greatest asset.', doThis: 'Embrace change, try new things, travel if possible', avoidThis: 'Resistance to change, recklessness, overindulgence', bestMonths: '5, 14, 23' },
  6: { title: 'Year of Responsibility & Love', theme: 'Nurture, commit, create harmony', desc: 'A year strongly focused on home, family, relationships, and responsibility. Marriages, births, and home purchases are common. You are called to serve and nurture the people you love.', doThis: 'Strengthen relationships, improve your home, commit', avoidThis: 'Avoiding responsibility, perfectionism, martyrdom', bestMonths: '6, 15, 24' },
  7: { title: 'Year of Inner Reflection', theme: 'Reflect, study, grow spiritually', desc: 'A deeply introspective year calling you inward. Study, research, meditation, and spiritual growth take centre stage. External results may seem slow — trust that inner development is preparing you for major outer success.', doThis: 'Study, meditate, rest, research, trust the process', avoidThis: 'Forcing external growth, isolation going too far, neglecting self-care', bestMonths: '7, 16, 25' },
  8: { title: 'Year of Power & Achievement', theme: 'Achieve, grow financially, claim your power', desc: 'Your peak achievement year. Financial investments, career advancement, business launches, and major decisions carry the strongest support of the entire 9-year cycle. Claim your power with confidence.', doThis: 'Invest, expand your business, negotiate, apply for leadership roles', avoidThis: 'Fear of success, avoiding financial decisions, abuse of power', bestMonths: '8, 17, 26' },
  9: { title: 'Year of Completion & Release', theme: 'Complete, release, prepare for renewal', desc: 'A year of endings, completions, and release. Let go of what no longer serves you — relationships, jobs, beliefs, possessions. This clearing prepares the ground for the powerful new 9-year cycle beginning next year.', doThis: 'Complete projects, forgive, declutter, travel, be generous', avoidThis: 'Starting major new ventures, holding on to what must go, new financial commitments', bestMonths: '9, 18, 27' },
};

export function getDigitsSum(numStr) {
  return String(numStr).replace(/\D/g, '').split('').map(Number).reduce((a, b) => a + b, 0);
}

export function reduceToSingleOrMaster(num) {
  while (num > 9 && num !== 11 && num !== 22 && num !== 33) {
    num = getDigitsSum(num.toString());
  }
  return num;
}

export function getCompatibilityKey(lp1, lp2) {
  // Reduce master numbers to single digit for compatibility lookup
  const a = [11, 22, 33].includes(lp1) ? reduceToSingleOrMaster(lp1) : lp1;
  const b = [11, 22, 33].includes(lp2) ? reduceToSingleOrMaster(lp2) : lp2;
  const lo = Math.min(a, b);
  const hi = Math.max(a, b);
  return `${lo}-${hi}`;
}
